"""initial database

Revision ID: b9945c2de2f1
Revises: 
Create Date: 2026-02-28 20:40:13.527711

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b9945c2de2f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('file_name', sa.String(length=150), nullable=False),
    sa.Column('upload_identification', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('articles_count', sa.Integer(), nullable=False),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_table('article_entries',
    sa.Column('file', sa.LargeBinary(), nullable=False),
    sa.Column('data_processed', sa.DateTime(), nullable=False),
    sa.Column('article_metadata', sa.JSON(), nullable=False),
    sa.Column('from_uploaded_zip_fk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_uploaded_zip_fk'], ['file_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_entries_data_processed'), 'article_entries', ['data_processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_entries_data_processed'), table_name='article_entries')
    op.drop_table('article_entries')
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
